###
POST http://192.168.11.130:3000/api/auth/login
Content-Type: application/json

{
    "email": "parent@gmail.com",
    "password": "123456"
}

###
POST http://192.168.11.141:3000/api/auth/send-verification-email
Content-Type: application/json

{
    "email": "abdomouak48@gmail.com"
}